@startuml

package logica{
Interface Instrumento
Class Musico
Class Banda 
Instrumento <|.. Guitarra
Instrumento <|.. Cuatro
Instrumento <|.. Piano
Instrumento <|.. Flauta
}

Principal -- Banda

Instrumento : afinar()
Instrumento : tocar()



Musico *-- Instrumento

Banda o-- Musico

Musico : Instrumento instrumento
Banda : Musico[] musicos

Banda : generar_instrumento()
Banda : afinar_banda()
Banda : tocar_banda()
@enduml